server:
  port: 8080
spring:  
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: lb://MOVIE
          predicates:
           - Path=/movie/**
        - id: catalogRoute
          uri: lb://CATALOG
          predicates:
           - Path=/catalog/**
        - id: serieRoute
          uri: lb://SERIE
          predicates:
           - Path=/serie/**