server:
  port: 8082
  servlet:
    context-path: /catalog/

spring:
  application:
    name: catalog-service
  zipkin:
    base-url: http://zipkin-service:9411/
  config:
    import: optional:configserver:http://config-server:8888  
  data:
    mongodb:
      uri: mongodb://root:password@mongo_catalog:27018/example?authSource=admin

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672

queue:
  movie:
    name: movieQueue
  serie:
    name: serieQueue

message: Catalog up

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  name: Micro serviço de catálogo
  author: Rener Almeida
  severity: Alto
